name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t woodson31/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true woodson31/react-test npm test

      #Take those images and push them to docker hub
      - run: docker build -t woodson31/multi-client ./client
      - run: docker build -t woodson31/multi-nginx ./nginx
      - run: docker build -t woodson31/multi-server ./server
      - run: docker build -t woodson31/multi-worker ./worker

      # Log in to the Docker CLI and push images to Docker Hub
      - run: docker push woodson31/multi-client
      - run: docker push woodson31/multi-nginx
      - run: docker push woodson31/multi-server
      - run: docker push woodson31/multi-worker

      - name: Generate deployment package
        # Create a zip file of the current directory, excluding .git files
        run: zip -r deploy.zip . -x '*.git*'

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "multi-docker"
          environment_name: "Multi-docker-env"
          existing_bucket_name: "elasticbeanstalk-eu-north-1-244704555729"
          version_label: ${{ github.sha }}
          region: "eu-north-1"
          deployment_package: "deploy.zip"
